### ISSUE TITLE
Hello World?

### ISSUE THREAD

**Issue by Dzamir** [MirkoMignini/heroku_app_skeleton#1]
I tried to run this program but I only get "Hello World". Why?

**Comment by fcroce** [comment]
I've also encountered the same issue here. I wanted to give my regards to the whole universe but the program seems to be limited to greet one world at a time only, possibly due to a bug.

**Comment by superpanza** [comment]
ฉันไม่ เข้าใจภาษาอังกฤษ มันจะมีอะไร พูดว่า " Hello World "?
